baseurl = "http://username.github.io"
languageCode = "en-us"
title = "Beautiful Hugo"
theme = "beautifulhugo"
pygmentsUseClasses = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  logo = "img/avatar-icon.png"
  subtitle = "Build a beautiful and simple website in minutes"

[Author]
  name = "Some Person"
  email = "youremail@domain.com"
  facebook = "username"
  github = "username"
  twitter = "username"
  linkedin = "pub/username/X/YYY/ZZZ"
  stackoverflow = "XXXXXXX/username"
  soundcloud = "username"
  wikipedia = "username"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2